name: rl-json-to-simple-feedback-markdown
description: Parse the report.rl.json file and produce a markdown simplefied summary
author: ReversingLabs

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: purple

# Define your inputs here.
inputs:
  rl_json_path:
    description: The path to the report.rl.json file.
    required: true

runs:
  using: node20
  main: dist/index.js
